backend:
  name: github
  repo: homesitezip/work
  branch: main

media_folder: "assets/images/portfolio"
public_folder: "/work/assets/images/portfolio"

collections:
  - name: "portfolio"
    label: "포트폴리오"
    folder: "_portfolio"
    create: true
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "이미지", name: "image", widget: "image" }
      - { label: "설명", name: "body", widget: "markdown" }
